// =========================================================
// Supabase browser client (singleton).
//
// Uses the public anon key — safe to ship to the browser because every table
// is guarded by Row Level Security keyed on auth.uid(). Privileged work (the
// translation provider, writing verified words) happens in edge functions with
// the service-role key, never here.
//
// Env (Vite): VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY.
// =========================================================

import { createClient } from "@supabase/supabase-js";
import type { Database } from "../types/database.types";

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

if (!url || !anonKey) {
  throw new Error(
    "VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set"
  );
}

// OUTPUT: a configured, SCHEMA-TYPED anon SupabaseClient (singleton). The
// `Database` generic (generated by `npm run gen:types` from the live schema)
// makes `.from()/.select()/.rpc()` return typed rows, so a renamed/removed
// column becomes a COMPILE error instead of a runtime surprise.
// CONSTRAINTS: fails FAST — throws at import if VITE_SUPABASE_URL / ANON_KEY are
// unset. This is intentional (a misconfigured app should not boot). It does NOT
// hurt tests: the unit suite replaces this whole module via `vi.mock`, so the
// check never runs there.
export const supabase = createClient<Database>(url, anonKey);
