// =========================================================
// ENGLISH part-of-speech tagger — the counterpart to kuromoji's Japanese tagging.
//
// WHY THIS EXISTS. `analyze()` routes Japanese to kuromoji and everything else to
// `segmentOnly`, which had no POS beyond a hand-written closed-class list. With English
// as the language being LEARNED that meant every capitalised name was offered as
// vocabulary: measured on en.wikinews, 23.5% of lookup keys missed the dictionary
// against 5.5% for ja.wikinews, the misses overwhelmingly proper nouns (UEFA, Abidal,
// Piraquara, WMAR). Each one is a paid MT call and a cache row.
//
// MODEL: averaged perceptron over UD UPOS tags, trained by scripts/build-pos-tagger.py
// on Universal Dependencies English-EWT (CC BY-SA 4.0 — see ATTRIBUTION.md). Measured
// on the held-out test split, through the SHIPPED quantized weights:
//   overall 94.2% · PROPN precision 84.8% / recall 85.5%
// A pure capitalisation heuristic — no model at all — was measured on the same split at
// 73.3% caught for 7.44% of content words wrongly demoted, i.e. LESS benefit at 2.5×
// the harm. That comparison is why this file is a model and not twenty lines of regex.
//
// ‼️ THE FEATURE FUNCTIONS BELOW ARE MIRRORED FROM scripts/build-pos-tagger.py AND MUST
// PRODUCE BYTE-IDENTICAL FEATURE STRINGS. The weights are meaningless against a
// different feature space, and the failure is silent — slightly worse tags, no error.
// tests/services/language/posEn.test.ts replays a golden fixture generated by the
// trainer and fails on any drift. Same discipline as the projection-version pin.
// =========================================================

/** The model as scripts/build-pos-tagger.py exports it. */
interface PosModel {
  /** Tag names, index-aligned with the ints used in `tagdict` and `weights`. */
  tags: string[];
  /** Weights are stored as integers scaled by this; see the trainer's SCALE. */
  scale: number;
  /** Surface → tag index, for words that are overwhelmingly one tag in training. */
  tagdict: Record<string, number>;
  /** Feature → flat [tagIndex, weight, tagIndex, weight, …]. */
  weights: Record<string, number[]>;
}

const START = ["-START-", "-START2-"];
const END = ["-END-", "-END2-"];

/**
 * Collapse the classes that would otherwise fill the feature space with hapaxes.
 * Mirrors `normalize` in the trainer — note it LOWERCASES, which is exactly why
 * `shape` below exists as a separate feature.
 */
function normalize(word: string): string {
  if (word.includes("-") && word[0] !== "-") return "!HYPHEN";
  // Python's str.isdigit() is true only when every character is a digit and the string
  // is non-empty. /^\d+$/ matches ASCII digits only, which is the same set for the
  // Latin-script text this tagger is ever handed.
  if (/^\d+$/.test(word)) return word.length === 4 ? "!YEAR" : "!DIGITS";
  return word.toLowerCase();
}

/**
 * Orthographic class, kept separate from the normalized form. This is the signal the
 * stock recipe throws away by lowercasing, and PROPN is the whole reason we need it.
 */
function shape(word: string): string {
  if (!word) return "";
  if (/^\d+$/.test(word)) return "d";
  // Python's isupper()/islower() ignore caseless characters and require at least one
  // cased character. Comparing against the case-mapped string reproduces that: a
  // caseless token ("!!!") equals both its upper and lower form, and Python answers
  // false for both — so test upper first and fall through, matching the trainer's order.
  const hasCased = word.toUpperCase() !== word.toLowerCase();
  if (hasCased && word === word.toUpperCase()) return "XX";
  if (word[0] === word[0].toUpperCase() && word[0] !== word[0].toLowerCase()) return "Xx";
  if (hasCased && word === word.toLowerCase()) return "xx";
  return "mixed";
}

/** Last up to 3 characters — Python's `word[-3:]`. */
function suffix(word: string): string {
  return word.slice(-3);
}

/**
 * The feature bag for one token. `context` is the normalized sentence padded with two
 * START and two END sentinels, so the token at sentence index `i` sits at context[i+2].
 */
function features(
  i: number,
  word: string,
  context: string[],
  prev: string,
  prev2: string,
): Map<string, number> {
  const feats = new Map<string, number>();
  const add = (...parts: string[]) => {
    const key = parts.join(" ");
    feats.set(key, (feats.get(key) ?? 0) + 1);
  };

  add("bias");
  add("i suffix", suffix(word));
  add("i pref1", word ? word[0] : "");
  add("i-1 tag", prev);
  add("i-2 tag", prev2);
  add("i tag+i-2 tag", prev, prev2);
  add("i word", context[i + 2]);
  add("i-1 tag+i word", prev, context[i + 2]);
  add("i-1 word", context[i + 1]);
  add("i-1 suffix", suffix(context[i + 1]));
  add("i-2 word", context[i]);
  add("i+1 word", context[i + 3]);
  add("i+1 suffix", suffix(context[i + 3]));
  add("i+2 word", context[i + 4]);
  // The three orthographic additions — all aimed at PROPN in context. A capitalised
  // word is weak evidence of a name; a capitalised word that is NOT sentence-initial is
  // strong evidence. Keeping them separate is what stops "Cats sleep" losing `Cats`.
  add("i shape", shape(word));
  add("i first", i === 0 ? "1" : "0");
  add("i shape+first", shape(word), i === 0 ? "1" : "0");
  return feats;
}

// --- model loading ---------------------------------------------------------

let modelPromise: Promise<PosModel> | null = null;

/**
 * Load the weights once, lazily. The file is ~2.8 MB, so it is a dynamic import and
 * therefore its own chunk: a Japanese-learning session never fetches it, and it is
 * fetched at most once per session. Same shape as the kuromoji lazy load, minus the
 * dictionary-file gymnastics — this is one plain JSON module, so no Vite plugin and no
 * Content-Encoding trap.
 */
function loadModel(): Promise<PosModel> {
  if (!modelPromise) {
    modelPromise = import("./posEnModel.json").then(
      (m) => (m.default ?? m) as unknown as PosModel,
    );
  }
  return modelPromise;
}

/** Start fetching the model without blocking — call when English input looks likely. */
export function warmEnglishTagger(): void {
  void loadModel().catch(() => {
    /* warming is best-effort; the real load reports its own failure */
  });
}

// --- tagging ---------------------------------------------------------------

/**
 * Tag one sentence's worth of surfaces, returning a UPOS tag per input token.
 *
 * Pure given the model: no I/O, no state carried between calls. The caller decides what
 * a sentence is — feeding the whole paragraph as one array still works, but the
 * sentence-initial feature then only fires on the very first token, which is precisely
 * the signal that separates "Cats" from "Abidal", so callers should split first.
 */
export function tagWithModel(model: PosModel, words: string[]): string[] {
  const context = [...START, ...words.map(normalize), ...END];
  let prev = START[0];
  let prev2 = START[1];
  const out: string[] = [];

  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    let tag: string | undefined;

    const known = model.tagdict[word];
    if (known !== undefined) {
      tag = model.tags[known];
    } else {
      const feats = features(i, word, context, prev, prev2);
      const scores = new Map<string, number>();
      for (const [feat, count] of feats) {
        const flat = model.weights[feat];
        if (!flat) continue;
        for (let k = 0; k < flat.length; k += 2) {
          const t = model.tags[flat[k]];
          scores.set(t, (scores.get(t) ?? 0) + flat[k + 1] * count);
        }
      }
      // Mirrors the trainer's `max(classes, key=lambda t: (scores[t], t))`: every tag
      // participates with a default of 0, and ties go to the lexicographically LARGEST
      // tag name. Both halves matter — a different tie-break silently changes output on
      // the tokens where the model has no opinion at all.
      let best = model.tags[0];
      let bestScore = scores.get(best) ?? 0;
      for (const t of model.tags) {
        const s = scores.get(t) ?? 0;
        if (s > bestScore || (s === bestScore && t > best)) {
          best = t;
          bestScore = s;
        }
      }
      tag = best;
    }

    out.push(tag);
    prev2 = prev;
    prev = tag;
  }
  return out;
}

/** Load the model if needed, then tag. Returns null if the model can't be loaded, so
 *  callers degrade to "no POS" rather than losing the text entirely. */
export async function tagEnglish(words: string[]): Promise<string[] | null> {
  if (words.length === 0) return [];
  try {
    const model = await loadModel();
    return tagWithModel(model, words);
  } catch (err) {
    console.warn("[posEn] English POS model unavailable; continuing without tags.", err);
    return null;
  }
}

// --- exported for the cross-runtime pin ------------------------------------
/** @internal test-only surface — the golden fixture drives these directly. */
export const __internal = { normalize, shape, features, loadModel };
