// =========================================================
// English BASE FORMS → the verifier `englishLemma` (reader) uses for regular
// -ing / -ed / -es inflections.
//
// WHY. The reader emits ONE lemma per token with no fallback, so a wrong lemma silently
// resolves a word to something else — which is why regular inflections were refused:
// "making" could be mak+ing or make+ing, "buses" bus+es or buse+s. Two facts now make
// them safe: the POS tagger (posEn.ts) says whether "building" is a VERB form or a
// NOUN in its own right, and THIS LIST says which candidate stem is a real word.
//
//   EN_VERB_FREQ  every single-token WordNet verb lemma → its wordfreq Zipf×100 (0 if
//                 unlisted), the frequency being the tiebreak when two stems are both
//                 verbs (putting → put, not putt).
//   EN_NOUNS      single-token WordNet noun lemmas at Zipf ≥ 3.0 (data/frequency/en.tsv,
//                 ≥ 300). The full noun list is 117k entries, most of them rare or
//                 multiword; the floor keeps the file small and the -es plural rule
//                 honest (it only ever resolves to a word a learner could meet).
//
// Ships as generated code for the same reason irregularsEn.generated.ts does: the lemma
// is computed synchronously in the browser before any query.
//
// SOURCE: WordNet 3.0 `dict/index.verb` + `dict/index.noun` (Princeton licence, already
// attributed) + data/frequency/en.tsv (wordfreq, CC-BY-SA, already attributed).
//   curl -L -O https://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz && tar -xzf WordNet-3.0.tar.gz
//   npm run build:en-bases -- ./WordNet-3.0/dict
// =========================================================
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/services/language/baseFormsEn.generated.ts");
const FREQ = join(ROOT, "data/frequency/en.tsv");
const NOUN_FLOOR = 300;

const dict = process.argv[2];
if (!dict) {
  console.error("usage: npm run build:en-bases -- <path to WordNet-3.0/dict>");
  process.exit(1);
}

/** Single-token lemmas of one index file (underscore = multiword, skipped). */
function readIndex(file: string): string[] {
  const out: string[] = [];
  for (const line of readFileSync(join(dict, file), "utf8").split("\n")) {
    if (line.startsWith("  ") || !line) continue; // licence header
    const lemma = line.slice(0, line.indexOf(" "));
    if (lemma.includes("_") || !/^[a-z][a-z'-]*$/.test(lemma)) continue;
    out.push(lemma);
  }
  return out;
}

const freq = new Map<string, number>();
for (const line of readFileSync(FREQ, "utf8").split("\n")) {
  const [w, f] = line.split("\t");
  if (w && f) freq.set(w, Number(f));
}

const verbs = readIndex("index.verb").sort();
const nouns = readIndex("index.noun")
  .filter((n) => (freq.get(n) ?? 0) >= NOUN_FLOOR)
  .sort();

const banner =
  `// GENERATED by scripts/build-en-bases.ts from Princeton WordNet 3.0 + wordfreq — DO NOT EDIT BY HAND.\n` +
  `// Regenerate: npm run build:en-bases -- ./WordNet-3.0/dict\n` +
  `//\n// The verifier behind the reader's regular -ing/-ed/-es lemma rules (lemmaEn.ts):\n` +
  `// a candidate stem is accepted only if it is a word here, under the tag the POS tagger\n` +
  `// gave the token. See the script header for what is in and what is left out.\n\n`;

const verbBody = verbs.map((v) => `  ${JSON.stringify(v)}: ${freq.get(v) ?? 0},`).join("\n");
const nounBody = nouns.map((n) => `  ${JSON.stringify(n)},`).join("\n");

writeFileSync(
  OUT,
  banner +
    `/** Every single-token WordNet verb → wordfreq Zipf×100 (0 = unlisted). ${verbs.length} entries. */\n` +
    `export const EN_VERB_FREQ: Readonly<Record<string, number>> = {\n${verbBody}\n};\n\n` +
    `/** Single-token WordNet nouns at Zipf ≥ ${NOUN_FLOOR / 100}. ${nouns.length} entries. */\n` +
    `export const EN_NOUNS: readonly string[] = [\n${nounBody}\n];\n`,
);
console.log(`verbs ${verbs.length} · nouns ${nouns.length} → ${OUT}`);
