// =========================================================
// MainViewController — the app's Capacitor bridge view controller. Exists solely
// to register LOCAL (app-target) plugins, which Capacitor does NOT auto-discover:
// registerPlugins() only loads built-ins + the npm plugins listed in
// capacitor.config.json's packageClassList (generated by `cap sync` from
// node_modules), so a plugin defined in this target is never picked up.
//
// capacitorDidLoad() runs right after the bridge is created and BEFORE the web
// content loads — the correct moment to register. registerPluginInstance (unlike
// registerPluginType) ignores the autoRegisterPlugins guard, so it always takes.
//
// Wired in Base.lproj/Main.storyboard (the scene's customClass → MainViewController).
// =========================================================
import Capacitor

class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(DigitalInkPlugin())
    }
}
