// =========================================================
// MainViewController — the app's Capacitor bridge view controller. Exists solely
// to register LOCAL (app-target) plugins, which Capacitor does NOT auto-discover:
// registerPlugins() only loads built-ins + the npm plugins listed in
// capacitor.config.json's packageClassList (generated by `cap sync` from
// node_modules), so a plugin defined in this target is never picked up.
//
// capacitorDidLoad() runs right after the bridge is created and BEFORE the web
// content loads — the correct moment to register. registerPluginInstance (unlike
// registerPluginType) ignores the autoRegisterPlugins guard, so it always takes.
//
// Wired in Base.lproj/Main.storyboard (the scene's customClass → MainViewController).
// =========================================================
import Capacitor

class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(DigitalInkPlugin())
        bridge?.registerPluginInstance(TextOcrPlugin())
    }

    // The scroll indicator down the right edge is drawn by WKWebView's own scroll
    // view, NOT by the page — CSS (`::-webkit-scrollbar`, `scrollbar-width`) cannot
    // reach the main frame's indicator, so hiding it web-side in common.css only
    // covers mobile browsers and this covers the app shell. Scrolling is unaffected;
    // only the indicator is suppressed. Native apps don't show a persistent track,
    // so this is what makes the shell look native rather than like a page.
    override func viewDidLoad() {
        super.viewDidLoad()
        if let scrollView = bridge?.webView?.scrollView {
            scrollView.showsVerticalScrollIndicator = false
            scrollView.showsHorizontalScrollIndicator = false
        }
    }
}
